# Generated by Django 2.0.5 on 2018-08-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splunkAutomation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='splunkquery',
            name='query_resolution_commands',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='splunkquery',
            name='resolve_conf',
            field=models.CharField(default='', max_length=50),
        ),
    ]
