# Generated by Django 2.0.5 on 2018-08-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splunkAutomation', '0002_auto_20180806_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splunkquery',
            name='query_text',
            field=models.CharField(max_length=1000),
        ),
    ]
