# Generated by Django 2.0.5 on 2018-08-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splunkAutomation', '0003_auto_20180809_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecuteCommands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_set', models.CharField(max_length=300)),
                ('organization', models.CharField(default='ukgrsps', max_length=10)),
                ('assembly', models.CharField(max_length=30)),
                ('environment', models.CharField(max_length=30)),
                ('platform', models.CharField(max_length=30)),
                ('component', models.CharField(max_length=30)),
                ('application', models.CharField(max_length=30)),
                ('resolve_conf', models.CharField(max_length=30)),
            ],
        ),
    ]
