# Generated by Django 2.0.5 on 2018-08-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splunkAutomation', '0005_splunkquery2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SplunkQuery2',
        ),
    ]
