# Generated by Django 2.0.5 on 2018-08-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splunkAutomation', '0006_delete_splunkquery2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExecuteCommands',
            new_name='ExecuteCommand',
        ),
    ]
