# Generated by Django 2.0.5 on 2018-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splunkAutomation', '0007_auto_20180810_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executecommand',
            name='resolve_conf',
            field=models.CharField(max_length=100),
        ),
    ]
